export const pricing = {
  painting: {
    project_design: { unit: "m2", price: 250 },
    preparation: { unit: "m2", price: 10 },
    putty_2_layers: { unit: "m2", price: 45 },
    priming: { unit: "m2", price: 10 },
    primer_paint: { unit: "m2", price: 15 },
    paint_2_layers: { unit: "m2", price: 25 },
    color_division: { unit: "lm", price: 5 },
    window_paint: { unit: "m2", price: 150 },
    door_paint: { unit: "pcs", price: 150 },
    radiator_paint: { unit: "rib", price: 25 },
    pipe_paint: { unit: "lm", price: 25 },
    coating_removal: { unit: "m2", price: 25 },
    wallpaper_install: { unit: "m2", price: 80 },
    wallpaper_remove: { unit: "m2", price: 20 },
    acrylic_corners: { unit: "lm", price: 7 },
    touchups: { unit: "m2", price: 20 },
  },

  drywall: {
    ceiling: { unit: "m2", price: 120 },
    wall_frame: { unit: "m2", price: 70 },
    wall_glue: { unit: "m2", price: 90 },
    partition_1_layer: { unit: "m2", price: 130 },
    partition_2_layer: { unit: "m2", price: 150 },
    ceiling_multi_level: { unit: "m2", price: 175 },
    attic_insulation: { unit: "m2", price: 200 },
    joint_fill: { unit: "lm", price: 20 },
    joint_putty: { unit: "lm", price: 20 },
    box_install: { unit: "lm", price: 150 },
    corner_bead_install: { unit: "lm", price: 20 },
  },

  tiling: {
    demolition_with_lift: { unit: "m2", price: 40 },
    demolition_no_lift: { unit: "m2", price: 65 },
    leveling: { unit: "m2", price: 40 },
    tile_10_15: { unit: "m2", price: 175 },
    tile_30_60: { unit: "m2", price: 140 },
    tile_60_120: { unit: "m2", price: 175 },
    mosaic: { unit: "lm", price: 250 },
    stone: { unit: "m2", price: 175 },
    plinth_cut: { unit: "lm", price: 50 },
    plinth_ready: { unit: "lm", price: 30 },
    step_tile: { unit: "m2", price: 170 },
    step_riser_tile: { unit: "m2", price: 170 },
    decorative_tile: { unit: "lm", price: 60 },
    ceramic_hole: { unit: "pcs", price: 35 },
    gres_hole: { unit: "pcs", price: 60 },
    stone_hole: { unit: "pcs", price: 70 },
    waterproofing: { unit: "m2", price: 40 },
    brick_slip_install: { unit: "m2", price: 150 },
    corner_polish_45: { unit: "lm", price: 80 },
    aluminum_trim_install: { unit: "lm", price: 35 },
    revision_hatch_tile: { unit: "pcs", price: 105 },
    tiled_shelf_install: { unit: "pcs", price: 230 },
    bathtub_enclosure: { unit: "pcs", price: 450 },
    shower_base_enclosure: { unit: "pcs", price: 230 },
  },

  flooring: {
    laminate: { unit: "m2", price: 60 },
    parquet_glue: { unit: "m2", price: 100 },
    parquet_click: { unit: "m2", price: 80 },
    carpet: { unit: "m2", price: 50 },
  },

  plumbing: {
    water_point_demolition: { unit: "pcs", price: 80 },
    fixture_demolition: { unit: "pcs", price: 80 },
    shower_drain_point: { unit: "pcs", price: 650 },
    water_point: { unit: "pcs", price: 600 },
    heating_point: { unit: "pcs", price: 300 },
    pipe_chasing: { unit: "lm", price: 40 },
    water_line_install: { unit: "lm", price: 20 },
    toilet_frame_install: { unit: "pcs", price: 300 },
    concealed_mixer_install: { unit: "pcs", price: 300 },
    standard_mixer_install: { unit: "pcs", price: 150 },
    bathtub_install: { unit: "pcs", price: 400 },
    toilet_install: { unit: "pcs", price: 250 },
    shower_base_install: { unit: "pcs", price: 200 },
    shower_install: { unit: "pcs", price: 300 },
    radiator_install: { unit: "pcs", price: 150 },
    shower_glass_install: { unit: "pcs", price: 200 },
    silicone_sealing: { unit: "lm", price: 20 },
    mirror_install: { unit: "m2", price: 100 },
    glass_shelf_install: { unit: "pcs", price: 100 },
  },

  electrical: {
    electric_point: { unit: "pcs", price: 140 },
    cable_tray_install: { unit: "lm", price: 30 },
    cable_routing: { unit: "lm", price: 5 },
    socket_install: { unit: "pcs", price: 30 },
    light_install: { unit: "pcs", price: 60 },
    electric_point_demolition: { unit: "pcs", price: 80 },
    wire_chasing: { unit: "pcs", price: 40 },
    switchboard_install: { unit: "module", price: 120 },
  },
};
